import 'dart:convert';

GetOrderSubjiListModel getOrderSubjiListModelFromJson(String str) =>
    GetOrderSubjiListModel.fromJson(json.decode(str));

String getOrderSubjiListModelToJson(GetOrderSubjiListModel data) =>
    json.encode(data.toJson());

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetOrderSubjiListModelOrderplacedSubjiList {
/*
{
  "id": "337",
  "day": "Fri",
  "sabji": "Jeeta alooo",
  "sId": "46",
  "so_number": "161",
  "tiffin_type": "Lunch",
  "subji_count": "1",
  "dt": "2024-04-19"
} 
*/

  String? id;
  String? day;
  String? sabji;
  String? sId;
  String? soNumber;
  String? tiffinType;
  String? subjiCount;
  String? dt;

  GetOrderSubjiListModelOrderplacedSubjiList({
    this.id,
    this.day,
    this.sabji,
    this.sId,
    this.soNumber,
    this.tiffinType,
    this.subjiCount,
    this.dt,
  });
  GetOrderSubjiListModelOrderplacedSubjiList.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    day = json['day']?.toString();
    sabji = json['sabji']?.toString();
    sId = json['sId']?.toString();
    soNumber = json['so_number']?.toString();
    tiffinType = json['tiffin_type']?.toString();
    subjiCount = json['subji_count']?.toString();
    dt = json['dt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['day'] = day;
    data['sabji'] = sabji;
    data['sId'] = sId;
    data['so_number'] = soNumber;
    data['tiffin_type'] = tiffinType;
    data['subji_count'] = subjiCount;
    data['dt'] = dt;
    return data;
  }
}

class GetOrderSubjiListModel {
/*
{
  "status_code": "200",
  "status": "success",
  "message": "Success",
  "orderplaced_subji_list": [
    {
      "id": "337",
      "day": "Fri",
      "sabji": "Jeeta alooo",
      "sId": "46",
      "so_number": "161",
      "tiffin_type": "Lunch",
      "subji_count": "1",
      "dt": "2024-04-19"
    }
  ]
} 
*/

  String? statusCode;
  String? status;
  String? message;
  List<GetOrderSubjiListModelOrderplacedSubjiList?>? orderplacedSubjiList;

  GetOrderSubjiListModel({
    this.statusCode,
    this.status,
    this.message,
    this.orderplacedSubjiList,
  });
  GetOrderSubjiListModel.fromJson(Map<String, dynamic> json) {
    statusCode = json['status_code']?.toString();
    status = json['status']?.toString();
    message = json['message']?.toString();
    if (json['orderplaced_subji_list'] != null) {
      final v = json['orderplaced_subji_list'];
      final arr0 = <GetOrderSubjiListModelOrderplacedSubjiList>[];
      v.forEach((v) {
        arr0.add(GetOrderSubjiListModelOrderplacedSubjiList.fromJson(v));
      });
      orderplacedSubjiList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status_code'] = statusCode;
    data['status'] = status;
    data['message'] = message;
    if (orderplacedSubjiList != null) {
      final v = orderplacedSubjiList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['orderplaced_subji_list'] = arr0;
    }
    return data;
  }
}
