import 'dart:convert';

GetAddOnItemCartModel getAddOnCartModelFromJson(String str) =>
    GetAddOnItemCartModel.fromJson(json.decode(str));

String getAddOnCartModelToJson(GetAddOnItemCartModel data) =>
    json.encode(data.toJson());

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetAddOnItemCartModelAddonItemList {
/*
{
  "pid": "24",
  "category_name": "Food",
  "subcategory_name": "Addonitem_food",
  "product_name": "item1",
  "product_code": "PC24",
  "description": "add on item 1",
  "product_image1": "https://softhubtechno.com/cloud_kitchen/uploads/dinner-61.jpg",
  "product_image2": "https://softhubtechno.com/cloud_kitchen/uploads/",
  "tax": "5",
  "price": "15",
  "mrp": "20",
  "item_add_status": "true",
  "item_add_quantity": "1",
  "item_add_cartid": "98"
} 
*/

  String? pid;
  String? categoryName;
  String? subcategoryName;
  String? productName;
  String? productCode;
  String? description;
  String? productImage1;
  String? productImage2;
  String? tax;
  String? price;
  String? mrp;
  String? itemAddStatus;
  String? itemAddQuantity;
  String? itemAddCartid;

  GetAddOnItemCartModelAddonItemList({
    this.pid,
    this.categoryName,
    this.subcategoryName,
    this.productName,
    this.productCode,
    this.description,
    this.productImage1,
    this.productImage2,
    this.tax,
    this.price,
    this.mrp,
    this.itemAddStatus,
    this.itemAddQuantity,
    this.itemAddCartid,
  });
  GetAddOnItemCartModelAddonItemList.fromJson(Map<String, dynamic> json) {
    pid = json['pid']?.toString();
    categoryName = json['category_name']?.toString();
    subcategoryName = json['subcategory_name']?.toString();
    productName = json['product_name']?.toString();
    productCode = json['product_code']?.toString();
    description = json['description']?.toString();
    productImage1 = json['product_image1']?.toString();
    productImage2 = json['product_image2']?.toString();
    tax = json['tax']?.toString();
    price = json['price']?.toString();
    mrp = json['mrp']?.toString();
    itemAddStatus = json['item_add_status']?.toString();
    itemAddQuantity = json['item_add_quantity']?.toString();
    itemAddCartid = json['item_add_cartid']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pid'] = pid;
    data['category_name'] = categoryName;
    data['subcategory_name'] = subcategoryName;
    data['product_name'] = productName;
    data['product_code'] = productCode;
    data['description'] = description;
    data['product_image1'] = productImage1;
    data['product_image2'] = productImage2;
    data['tax'] = tax;
    data['price'] = price;
    data['mrp'] = mrp;
    data['item_add_status'] = itemAddStatus;
    data['item_add_quantity'] = itemAddQuantity;
    data['item_add_cartid'] = itemAddCartid;
    return data;
  }
}

class GetAddOnItemCartModel {
/*
{
  "status_code": "200",
  "status": "success",
  "message": "Add on item list",
  "addon_item_list": [
    {
      "pid": "24",
      "category_name": "Food",
      "subcategory_name": "Addonitem_food",
      "product_name": "item1",
      "product_code": "PC24",
      "description": "add on item 1",
      "product_image1": "https://softhubtechno.com/cloud_kitchen/uploads/dinner-61.jpg",
      "product_image2": "https://softhubtechno.com/cloud_kitchen/uploads/",
      "tax": "5",
      "price": "15",
      "mrp": "20",
      "item_add_status": "true",
      "item_add_quantity": "1",
      "item_add_cartid": "98"
    }
  ]
} 
*/

  String? statusCode;
  String? status;
  String? message;
  List<GetAddOnItemCartModelAddonItemList?>? addonItemList;

  GetAddOnItemCartModel({
    this.statusCode,
    this.status,
    this.message,
    this.addonItemList,
  });
  GetAddOnItemCartModel.fromJson(Map<String, dynamic> json) {
    statusCode = json['status_code']?.toString();
    status = json['status']?.toString();
    message = json['message']?.toString();
    if (json['addon_item_list'] != null) {
      final v = json['addon_item_list'];
      final arr0 = <GetAddOnItemCartModelAddonItemList>[];
      v.forEach((v) {
        arr0.add(GetAddOnItemCartModelAddonItemList.fromJson(v));
      });
      addonItemList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status_code'] = statusCode;
    data['status'] = status;
    data['message'] = message;
    if (addonItemList != null) {
      final v = addonItemList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['addon_item_list'] = arr0;
    }
    return data;
  }
}
