import 'dart:convert';

AddressListTypewiseModel getAddressListTypewiseModelFromJson(String str) =>
    AddressListTypewiseModel.fromJson(json.decode(str));

String getAddressListTypewiseModelToJson(AddressListTypewiseModel data) =>
    json.encode(data.toJson());
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddressListTypewiseModelTypewiseAddressList {
/*
{
  "id": "8",
  "customer_code": "VK11",
  "user_type": "User",
  "phone": "9325612162",
  "address_type": "Home",
  "state": "Gujarat",
  "city": "Surat",
  "pincode": "395004",
  "address": "1650, 1650, Amphitheatre Parkway, , Mountain View, California 94043, United States",
  "lat_long": "37.4219985 -122.0839999",
  "receivers_name": "Monika",
  "contact_no": "9325612162",
  "date": "2024-02-26"
} 
*/

  String? id;
  String? customerCode;
  String? userType;
  String? phone;
  String? addressType;
  String? state;
  String? city;
  String? pincode;
  String? address;
  String? latLong;
  String? receiversName;
  String? contactNo;
  String? date;

  AddressListTypewiseModelTypewiseAddressList({
    this.id,
    this.customerCode,
    this.userType,
    this.phone,
    this.addressType,
    this.state,
    this.city,
    this.pincode,
    this.address,
    this.latLong,
    this.receiversName,
    this.contactNo,
    this.date,
  });
  AddressListTypewiseModelTypewiseAddressList.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    customerCode = json['customer_code']?.toString();
    userType = json['user_type']?.toString();
    phone = json['phone']?.toString();
    addressType = json['address_type']?.toString();
    state = json['state']?.toString();
    city = json['city']?.toString();
    pincode = json['pincode']?.toString();
    address = json['address']?.toString();
    latLong = json['lat_long']?.toString();
    receiversName = json['receivers_name']?.toString();
    contactNo = json['contact_no']?.toString();
    date = json['date']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['customer_code'] = customerCode;
    data['user_type'] = userType;
    data['phone'] = phone;
    data['address_type'] = addressType;
    data['state'] = state;
    data['city'] = city;
    data['pincode'] = pincode;
    data['address'] = address;
    data['lat_long'] = latLong;
    data['receivers_name'] = receiversName;
    data['contact_no'] = contactNo;
    data['date'] = date;
    return data;
  }
}

class AddressListTypewiseModel {
/*
{
  "status_code": "200",
  "status": "success",
  "message": "Address List Typewise",
  "typewise_address_list": [
    {
      "id": "8",
      "customer_code": "VK11",
      "user_type": "User",
      "phone": "9325612162",
      "address_type": "Home",
      "state": "Gujarat",
      "city": "Surat",
      "pincode": "395004",
      "address": "1650, 1650, Amphitheatre Parkway, , Mountain View, California 94043, United States",
      "lat_long": "37.4219985 -122.0839999",
      "receivers_name": "Monika",
      "contact_no": "9325612162",
      "date": "2024-02-26"
    }
  ]
} 
*/

  String? statusCode;
  String? status;
  String? message;
  List<AddressListTypewiseModelTypewiseAddressList?>? typewiseAddressList;

  AddressListTypewiseModel({
    this.statusCode,
    this.status,
    this.message,
    this.typewiseAddressList,
  });
  AddressListTypewiseModel.fromJson(Map<String, dynamic> json) {
    statusCode = json['status_code']?.toString();
    status = json['status']?.toString();
    message = json['message']?.toString();
  if (json['typewise_address_list'] != null) {
  final v = json['typewise_address_list'];
  final arr0 = <AddressListTypewiseModelTypewiseAddressList>[];
  v.forEach((v) {
  arr0.add(AddressListTypewiseModelTypewiseAddressList.fromJson(v));
  });
    typewiseAddressList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status_code'] = statusCode;
    data['status'] = status;
    data['message'] = message;
    if (typewiseAddressList != null) {
      final v = typewiseAddressList;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['typewise_address_list'] = arr0;
    }
    return data;
  }
}
