import 'dart:convert';

GetBranchListModel getBranchListModelFromJson(String str) =>
    GetBranchListModel.fromJson(json.decode(str));

String getBranchListModelToJson(GetBranchListModel data) =>
    json.encode(data.toJson());

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetBranchListModelBranchList {
/*
{
  "id": "3",
  "branch_name": "Hadapsar",
  "address": "Seasons Mall ,Magarpatta, Hadapsar, Pune, Maharashtra 411013",
  "login_id": "mr0033",
  "lat_long": "18.519859666983127, 73.93133843966072"
} 
*/

  String? id;
  String? branchName;
  String? address;
  String? loginId;
  String? latLong;

  GetBranchListModelBranchList({
    this.id,
    this.branchName,
    this.address,
    this.loginId,
    this.latLong,
  });
  GetBranchListModelBranchList.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    branchName = json['branch_name']?.toString();
    address = json['address']?.toString();
    loginId = json['login_id']?.toString();
    latLong = json['lat_long']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['branch_name'] = branchName;
    data['address'] = address;
    data['login_id'] = loginId;
    data['lat_long'] = latLong;
    return data;
  }
}

class GetBranchListModel {
/*
{
  "status_code": "200",
  "status": "success",
  "message": "Success",
  "branch_list": [
    {
      "id": "3",
      "branch_name": "Hadapsar",
      "address": "Seasons Mall ,Magarpatta, Hadapsar, Pune, Maharashtra 411013",
      "login_id": "mr0033",
      "lat_long": "18.519859666983127, 73.93133843966072"
    }
  ]
} 
*/

  String? statusCode;
  String? status;
  String? message;
  List<GetBranchListModelBranchList?>? branchList;

  GetBranchListModel({
    this.statusCode,
    this.status,
    this.message,
    this.branchList,
  });
  GetBranchListModel.fromJson(Map<String, dynamic> json) {
    statusCode = json['status_code']?.toString();
    status = json['status']?.toString();
    message = json['message']?.toString();
    if (json['branch_list'] != null) {
      final v = json['branch_list'];
      final arr0 = <GetBranchListModelBranchList>[];
      v.forEach((v) {
        arr0.add(GetBranchListModelBranchList.fromJson(v));
      });
      branchList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status_code'] = statusCode;
    data['status'] = status;
    data['message'] = message;
    if (branchList != null) {
      final v = branchList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['branch_list'] = arr0;
    }
    return data;
  }
}
