import 'dart:convert';

PostTIffinOrderModel postTifinOrderModelFromJson(String str) =>
    PostTIffinOrderModel.fromJson(json.decode(str));

String postTifinOrderModelToJson(PostTIffinOrderModel data) => json.encode(data.toJson());

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PostTIffinOrderModelTiffinOrderDetails {
/*
{
  "id": "70",
  "customer_name": "Monika",
  "customer_code": "VK11",
  "so_number": "69",
  "phone": "9325612162",
  "address": "FR79+MC6, Service Rd, Wadgaon Budruk, Narhe, Pune, Maharashtra 411041",
  "order_dt": "2024-03-15",
  "order_time": "01:52:27",
  "delivery_charges": "40",
  "receivers_name": "monika gite",
  "billto_phone": "9090909090",
  "branch": "sdd",
  "order_category": "Tiffin",
  "coupon_code": "",
  "coupon_amount": "",
  "tiffin_count": "22",
  "username": "VK11",
  "user_type": "User"
} 
*/

  String? id;
  String? customerName;
  String? customerCode;
  String? soNumber;
  String? phone;
  String? address;
  String? orderDt;
  String? orderTime;
  String? deliveryCharges;
  String? receiversName;
  String? billtoPhone;
  String? branch;
  String? orderCategory;
  String? couponCode;
  String? couponAmount;
  String? tiffinCount;
  String? username;
  String? userType;

  PostTIffinOrderModelTiffinOrderDetails({
    this.id,
    this.customerName,
    this.customerCode,
    this.soNumber,
    this.phone,
    this.address,
    this.orderDt,
    this.orderTime,
    this.deliveryCharges,
    this.receiversName,
    this.billtoPhone,
    this.branch,
    this.orderCategory,
    this.couponCode,
    this.couponAmount,
    this.tiffinCount,
    this.username,
    this.userType,
  });
  PostTIffinOrderModelTiffinOrderDetails.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    customerName = json['customer_name']?.toString();
    customerCode = json['customer_code']?.toString();
    soNumber = json['so_number']?.toString();
    phone = json['phone']?.toString();
    address = json['address']?.toString();
    orderDt = json['order_dt']?.toString();
    orderTime = json['order_time']?.toString();
    deliveryCharges = json['delivery_charges']?.toString();
    receiversName = json['receivers_name']?.toString();
    billtoPhone = json['billto_phone']?.toString();
    branch = json['branch']?.toString();
    orderCategory = json['order_category']?.toString();
    couponCode = json['coupon_code']?.toString();
    couponAmount = json['coupon_amount']?.toString();
    tiffinCount = json['tiffin_count']?.toString();
    username = json['username']?.toString();
    userType = json['user_type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['customer_name'] = customerName;
    data['customer_code'] = customerCode;
    data['so_number'] = soNumber;
    data['phone'] = phone;
    data['address'] = address;
    data['order_dt'] = orderDt;
    data['order_time'] = orderTime;
    data['delivery_charges'] = deliveryCharges;
    data['receivers_name'] = receiversName;
    data['billto_phone'] = billtoPhone;
    data['branch'] = branch;
    data['order_category'] = orderCategory;
    data['coupon_code'] = couponCode;
    data['coupon_amount'] = couponAmount;
    data['tiffin_count'] = tiffinCount;
    data['username'] = username;
    data['user_type'] = userType;
    return data;
  }
}

class PostTIffinOrderModel {
/*
{
  "status_code": "200",
  "status": "success",
  "message": "Tiffin Order Place Successfully...",
  "Tiffin_Order_Details": {
    "id": "70",
    "customer_name": "Monika",
    "customer_code": "VK11",
    "so_number": "69",
    "phone": "9325612162",
    "address": "FR79+MC6, Service Rd, Wadgaon Budruk, Narhe, Pune, Maharashtra 411041",
    "order_dt": "2024-03-15",
    "order_time": "01:52:27",
    "delivery_charges": "40",
    "receivers_name": "monika gite",
    "billto_phone": "9090909090",
    "branch": "sdd",
    "order_category": "Tiffin",
    "coupon_code": "",
    "coupon_amount": "",
    "tiffin_count": "22",
    "username": "VK11",
    "user_type": "User"
  }
} 
*/

  String? statusCode;
  String? status;
  String? message;
  PostTIffinOrderModelTiffinOrderDetails? TiffinOrderDetails;

  PostTIffinOrderModel({
    this.statusCode,
    this.status,
    this.message,
    this.TiffinOrderDetails,
  });
  PostTIffinOrderModel.fromJson(Map<String, dynamic> json) {
    statusCode = json['status_code']?.toString();
    status = json['status']?.toString();
    message = json['message']?.toString();
    TiffinOrderDetails = (json['Tiffin_Order_Details'] != null) ? PostTIffinOrderModelTiffinOrderDetails.fromJson(json['Tiffin_Order_Details']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status_code'] = statusCode;
    data['status'] = status;
    data['message'] = message;
    if (TiffinOrderDetails != null) {
      data['Tiffin_Order_Details'] = TiffinOrderDetails!.toJson();
    }
    return data;
  }
}
